### ISSUE TITLE
Crash when trying to load on server

### ISSUE THREAD

**Issue by Leonime** [VincentHuto/HutosLib#1]
Using hutoslib-4.3.0 for Minecraft 1.19.2
I'm attaching the log:
[latest.log](https://github.com/VincentHuto/HutosLib/files/11669163/latest.log)
Also the crash report:
[crash-2023-06-06_13.48.19-fml.txt](https://github.com/VincentHuto/HutosLib/files/11669191/crash-2023-06-06_13.48.19-fml.txt)
Don't know if you need any more info

**Comment by VincentHuto** [comment]
Hey thanks for reporting, I'll take a look at it if/when I can find some time, shouldn't be hard, but I have to admit I've been waiting till 1.20 comes out to commit to much time in modding again

**Comment by VincentHuto** [comment]
> Using hutoslib-4.3.0 for Minecraft 1.19.2 I'm attaching the log: [latest.log](https://github.com/VincentHuto/HutosLib/files/11669163/latest.log) Also the crash report: [crash-2023-06-06_13.48.19-fml.txt](https://github.com/VincentHuto/HutosLib/files/11669191/crash-2023-06-06_13.48.19-fml.txt) Don't know if you need any more info

This has been fixed in the newest update 4.5.0
